# 0-1Learning

![alt text](../../static/common/svg/luoxiaosheng.svg "公众号")
![alt text](../../static/common/svg/luoxiaosheng_learning.svg "学习")
![alt text](../../static/common/svg/luoxiaosheng_wechat.svg "微信")
![alt text](../../static/common/svg/luoxiaosheng_gitee.svg "码云")

## 异常处理

### 要点
* 异常类的继承关系
* 抓抛模型
* try-catch-finally关键字
* throw和throws关键字

### 异常是什么
* 程序运行过程时都可能发生会打断程序正常执行的事件。比如除数为零0、数组下标越界、文件找不到、内存不足等。

* Java异常处理
    * 利用抓抛模型处理异常
    * 利用面向对象的方法来处理异常

### 异常类型
* 产生一个异常就是由系统（JVM）自动的实例化一个异常类的 对象。
    * 称为抛出异常

* 异常的继承树
    * 检查性异常（checked exception）
    * 非检查性异常（unchecked exception）
![alt text](../../static/java/java_exception.png "")

### 方法调用堆栈
* 后进先出

### 抛出异常对象
``````
Exception in thread "main" 
    java.lang.ArrayIndexOutOfBoundsException: 5 
    at Sample.methodThree(Sample.java:17)
    at Sample.methodTwo(Sample.java:13) 
    at Sample.methodOne(Sample.java:9) 
    at Sample.main(Sample.java:5)
Press any key to continue...
``````

### 捕获异常
* try块和catch块try块和catch块
* catch块，是用来捕获并处理try块抛出的异常的代码块。没有try块，catch块不能单独存在。我们可以有多个catch块，以捕获不同类型的异常。

``````
try{
	System.out.println(arr[3]);
	System.out.println("Three"); 19	
} catch(ArrayIndexOutOfBoundsException ex){
    System.out.println("catched"); 
}

``````

### 抓抛模型
* 如果程序抛出多个不同类型的异常，我们需要多个catch()语句来处理。
* 和特殊异常类相关联的catch()块必须写在和普 通异常类相关联的catch() 之前。

### finally块
* 在try-catch之后存在finally 块，表示执行try-catch块以后，无论有无抛出Exception，最后必须执行finally块的代码。
* 通常在finally块中编写将资源返还给系统的语句，它一般包括：
* 释放动态分配的内存块
* 关闭文件
* 关闭数据库结果集
* 关闭与数据库建立的连接

### throw语句
* 二次抛出
``````
catch(Exception e) {
System.out.println("一个异常已经产生"); throw e;
}

throw new IOException();
``````

#### throws声明方法抛出异常
* throws用来声明一个成员函数可能抛出的各种“异常”
* 位置：函数头的后面
* 方法中如果抛出：
    * 非检查性异常：去除Bug，直到不抛出异常；
    * 检查性异常
* 不进行处理，编译通不过。
* 在该函数内try-catch，把异常处理掉。那么不往上一级抛出异常，程序正常执行，上一级方法并不知道曾经产生异常。
* 用throws声明方法抛出异常，不进行处理。谁调用谁 负责处理。


``````
01	class ThrowsDemo{
02	public static void proc( ) throws IOException{ 
03		System.out.println("inside proc");
04		throw new IOException("ThrowsDemo"); 
05	}
06	public static void main(String args[ ]){ 
07		try{
08	        proc ();
09	    }catch(IOException e){
10		    System.out.println("caught"+e); 
11	    }
12	}
13 }
``````

### 用户自定义异常

* 如果Java提供的异常类型不能满足程序设计的需要，我们可以
定义自己的异常类型。

* 继承Exception类或其子类












